### PR TITLE
Ajout d’icônes sur la page d’index.

### PR DESCRIPTION
**Pull request by Lukc**
@blankoworld, les icônes sont importées des CDN. Il faudrait probablement faire ça un poil mieux.

### CODE REVIEW

**Comment by blankoworld** [comment]
@Lukc I include FontAwesome Icon Library. Is that OK for you?

**Comment by Lukc** [comment]
@blankoworld, including the library would indeed be the right thing to do. :)

How about the feature itself though? Are those icons good enough for merge? Should other places be “illustrated” as well? Can someone review the change?

**Comment by Lukc** [comment]
@blankoworld, is this ready for merge?

**Comment by blankoworld** [comment]
@Lukc : Ready!

**Pull request merged**
